[mockup]
path = 'examples/template_1.jpg'
title_pos = [280, 65]
image_pos = [70, 155, 490, 580]
text_pos = [70, 625, 490, 790]

[card.'Patrick']
path = 'examples/origin/patrick.jpg'
output = 'examples/output/patrick_card.jpg'
text = 'Este é o patrick, amigo do bob esponja tal tal tal, é isso aí. Uma carta muito boa.'

[card.'Minha célula']
path = 'examples/origin/pepa.jpg'
output = 'examples/output/pepa_card.jpg'
text = 'Esta é a Pepa Pig Deformada. Não sei muita coisa sobre ela.'